version: '3'

volumes:
    web:
        name: web
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/web
    db:
        name: db
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/db

networks:
    inception:
        name: inception

services:
    nginx:
        image: nginx
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - web:/var/www/wp
        networks:
            - inception
        ports:
            - 443:443
        depends_on:
            - wordpress
        restart: always
        environment:
            - DOMAIN=${DOMAIN}
            - SSLKEY=${SSLKEY}
            - SSLCERT=${SSLCERT}
    wordpress:
        image: wordpress
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - web:/var/www/wp
        networks:
            - inception
        depends_on:
            - mariadb
        restart: always
        environment:
            - USER=${USER}
            - DBHOST=${DBHOST}
            - DOMAIN=${DOMAIN}
            - DATABASE=${DATABASE}
            - PASSWORD=${PASSWORD}
            - WP_ADMIN=${WP_ADMIN}
            - WP_ADMIN_PASSWD=${WP_ADMIN_PASSWD}
    mariadb:
        image: mariadb
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        networks:
            - inception
        restart: always
        environment:
            - USER=${USER}
            - DATABASE=${DATABASE}
            - PASSWORD=${PASSWORD}
            - ROOT_PASSWORD=${ROOT_PASSWORD}
