version: '3'

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - ~/data/web:/var/www/wp
        networks:
            - inception
        ports:
            - 443:443
        depends_on:
            - wordpress
        restart: always
        environment:
            - DOMAIN=${DOMAIN}
            - SSLKEY=${SSLKEY}
            - SSLCERT=${SSLCERT}
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - ~/data/web:/var/www/wp
        networks:
            - inception
        depends_on:
            - mariadb
        restart: always
        environment:
            - USER=${USER}
            - DBHOST=${DBHOST}
            - DOMAIN=${DOMAIN}
            - DATABASE=${DATABASE}
            - PASSWORD=${PASSWORD}
            - WP_ADMIN=${WP_ADMIN}
            - WP_ADMIN_PASSWD=${WP_ADMIN_PASSWD}
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - ~/data/db:/var/lib/mysql
        networks:
            - inception
        restart: always
        environment:
            - USER=${USER}
            - DATABASE=${DATABASE}
            - PASSWORD=${PASSWORD}
            - ROOT_PASSWORD=${ROOT_PASSWORD}
