version: '3'

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - ~/data/web:/var/www/html
        networks:
            - inception
        ports:
            - 443:443
        restart: always
        depends_on:
            - wordpress
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - ~/data/web:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        restart: always
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - ~/data/db:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
        restart: always
