version: '3'

volumes:
    db:
        name: db
        driver: local
        driver_opts:
            device: /home/zhabri/data/db
            o: bind
            type: none
    web:
        name: web
        driver_opts:
            device: /home/zhabri/data/web
            o: bind
            type: none

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - db:/var/www/html
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress
        restart: always
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - db:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        restart: always
        # depends_on:
        #     - mariadb
    # mariadb:
    #     container_name: mariadb
    #     build: ./requirements/mariadb
    #     volumes:
    #         - db:/var/lib/mysql
    #     networks:
    #         - inception
    #     env_file:
    #         - .env
    #     restart: always
