version: '3'

volumes:
    db:
        name: db
        driver: local
        driver_opts:
            device: /home/${USER}/data/db
            type: none
            o: bind
    web:
        name: web
        driver: local
        driver_opts:
            device: /home/${USER}/data/web
            type: none
            o: bind

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - web:/var/www/html
        networks:
            - inception
        ports:
            - 443:443
        depends_on:
            - wordpress
        restart: always
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - web:/var/www/html
        networks:
            - inception
        env_file:
            - .env
        depends_on:
            - mariadb
        restart: always
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - db:/var/lib/mysql
        networks:
            - inception
        env_file:
            - .env
        restart: always
