#!/bin/sh

DATABASE=zakdb
USER=zak
ROOT_PASSWORD=zak
PASSWORD=zak

set_db () {
    mysql_install_db --user=mysql --datadir=/var/lib/mysql --skip-test-db

    #https://github.com/yobasystems/alpine-mariadb
    /usr/bin/mysqld \
        --user=mysql \
        --bootstrap <<- EOF
        USE mysql;
        FLUSH PRIVILEGES ;
        GRANT ALL ON *.* TO 'root'@'%' identified by '$ROOT_PASSWORD' WITH GRANT OPTION ;
        SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${ROOT_PASSWORD}') ;
        CREATE DATABASE IF NOT EXISTS $DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;
        GRANT ALL ON $DATABASE.* to '$USER'@'%' IDENTIFIED BY '$PASSWORD';
        FLUSH PRIVILEGES ;
EOF

    #https://wiki.alpinelinux.org/wiki/MariaDB
    sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf
    sed -i "s|.*skip-networking.*|skip-networking=OFF|g" /etc/my.cnf.d/mariadb-server.cnf
}

[ ! -d /var/lib/mysql/mysql ] && set_db

exec /usr/bin/mysqld --user=mysql --console
