#!/bin/sh

install_db () {
    mysql_install_db --user=mysql --datadir=/var/lib/mysql --skip-test-db

    # https://github.com/yobasystems/alpine-mariadb
    /usr/bin/mysqld \
        --user=mysql \
        --bootstrap <<- EOF
		USE mysql;
		FLUSH PRIVILEGES ;
		ALTER USER 'root'@'localhost' IDENTIFIED BY '$ROOT_PASSWORD';
		CREATE DATABASE IF NOT EXISTS $DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;
		GRANT ALL ON $DATABASE.* to '$USER'@'%' IDENTIFIED BY '$PASSWORD';
		FLUSH PRIVILEGES ;
EOF

    # https://wiki.alpinelinux.org/wiki/MariaDB
    sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf
    sed -i "s|.*skip-networking.*|skip-networking=OFF\nskip-grant-tables=0|g" /etc/my.cnf.d/mariadb-server.cnf
}

[ ! -d /var/lib/mysql/mysql ] && install_db

exec /usr/bin/mysqld --user=mysql --console
