volumes:
    data:
        name: data
        driver_opts:
            device: /home/zhabri/data
            type: bind

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./srcs/nginx
        volumes:
            - data:/var/www/html
        networks:
            - inception
        ports:
            - "443:443"
        restart: always
