version: '3'

volumes:
    db:
        name: db
        driver_opts:
            device: /home/zhabri/data/db
            type: bind
    web:
        name: web
        driver_opts:
            device: /home/zhabri/data/web
            type: bind

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./srcs/nginx/
        volumes:
            - db:/var/www/html/
        networks:
            - inception
        ports:
            - "443:443"
        restart: always
    wordpress:
        container_name: wordpress
        build: ./srcs/wordpress/
        volumes:
            - db:/var/www/html/
        networks:
            - inception
        env_file:
            - .env
        restart: always
