#!/bin/sh

[ ! -d /var/lib/mysql/mysql ] && mysql_install_db --user=mysql --ldata=/var/lib/mysql --skip-test-db

MYSQL_DATABASE=zakdb
MYSQL_USER=zak
MYSQL_PASSWORD=zak

/usr/bin/mysqld \
    --user=mysql \
    --bootstrap \
    --verbose=0 \
    --skip-name-resolve \
    --skip-networking=0/usr/bin/mysqld <<-EOF
    USE mysql;
    FLUSH PRIVILEGES ;
    GRANT ALL ON *.* TO 'root'@'%' identified by '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION ;
    GRANT ALL ON *.* TO 'root'@'localhost' identified by '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION ;
    SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${MYSQL_ROOT_PASSWORD}') ;
    CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci;
    GRANT ALL ON $MYSQL_DATABASE.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
    FLUSH PRIVILEGES ;
EOF

exec /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0 $@
