#!/bin/sh

DOMAIN=zhabri.42.fr
SSLKEY=/etc/ssl/private/nginx.key
SSLCERT=/etc/ssl/certs/nginx.crt

gen_ssl_key() {
    openssl req -newkey rsa:2048 \
    -nodes -keyout $SSLKEY \
    -x509 -days 365 -out $SSLCERT \
    -subj "/CN=$DOMAIN"

    chmod 600 /etc/ssl/private/nginx.key
}

gen_nginx_conf() {
    [ -f /etc/nginx/http.d/default.conf ] && rm /etc/nginx/http.d/default.conf
    cat << EOF > /etc/nginx/http.d/my.conf
    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name $DOMAIN www.$DOMAIN;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate $SSLCERT;
        ssl_certificate_key $SSLKEY;

        root /var/www/wp;
        index index.php index.html;

        location / {
            autoindex off;
            try_files \$uri \$uri/ /index.php?\$args;
        }

        location ~ \.php\$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        }
    }
EOF
}

[ ! -d /var/www/wp ] && mkdir -p /var/www/wp
[ ! -f /etc/ssl/private/nginx.key ] && gen_ssl_key
[ ! -f /etc/nginx/http.d/my.conf ] && gen_nginx_conf

exec nginx -g "daemon off;"
